scrape_configs:
  - job_name: 'sistema_contabil_spring_app'
    metrics_path: '/actuator/prometheus' # O caminho do endpoint que configuramos
    scrape_interval: 15s # A cada quantos segundos o Prometheus deve coletar os dados
    static_configs:
      - targets: ['localhost:8080'] # O endereço da sua aplicação Spring
